project:
  type: website

website:
  title: "crecoolt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - validation.qmd
      - intervention.qmd
      - stewardship.qmd
      

format:
  html:
    theme:
      - zephyr
    css: styles.css
    toc: true

editor: visual

